/* =============================================================================
 * fake-bs-sim.cc
 *
 * Physics-Constrained Cooperative Detection and Localization of
 * Fake Base Stations Using Timing Advance
 *
 * ns-3.39 LTE simulation:
 *   - Grid of legal eNBs (gridSize x gridSize)
 *   - One fake eNB configured with the same ECGI as one legal cell (--fakeEci)
 *   - UEs with random-waypoint mobility
 *   - 1-second periodic measurement report as configured by eNB (MeasReportConfig)
 *
 * ECGI-based measurement model:
 *   In real LTE, eNB sends RRCConnectionReconfiguration containing a
 *   MeasurementConfiguration IE that instructs the UE to:
 *     - Measure RSRP/RSRQ for cells specified in measObjectEUTRA
 *     - Include the ECGI of each reported cell (cellIdReporting = enabled)
 *     - Report periodically at the configured interval
 *   This simulation models that configuration via MeasReportConfig.
 *
 *   When fake and legal share an ECGI, the UE sees the stronger signal (max
 *   RSRP) at that ECGI.  CC-PCV compares against the known LEGAL position →
 *   anomalous residual → detection.
 *
 * Outputs (outputDir/):
 *   simulation.log      — full structured log (DEBUG level)
 *   measurements.csv    — time_sec, imsi, ue_x, ue_y, ecgi,
 *                         cell_role (S/N), rsrp_dbm, timing_advance
 *   cell_database.csv   — all cells: ecgi, pos_x, pos_y, tx_power_dbm, is_fake
 *   legal_cell_map.csv  — legal cells only: ecgi, pos_x, pos_y, tx_power_dbm
 *   ccpcv_results.csv   — time_sec, ecgi, residual, status
 *
 * TA NOTE:
 *   ns-3.39 has no TimingAdvance trace source on LteUeRrc.
 *   TA derived geometrically: TA = round(dist_m / 78.125)
 *
 *   LteUePhy::ReportCurrentCellRsrpSinr never fires in RRC_CONNECTED state.
 *   Measurements generated by PeriodicMeasure() via geometric path-loss.
 *
 * Run:
 *   ./ns3 run "fake-bs-sim --gridSize=3 --numUe=20 --simTime=30 --fakeEci=1"
 * =============================================================================
 */

#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/mobility-module.h"
#include "ns3/lte-module.h"
#include "ns3/applications-module.h"
#include "ns3/point-to-point-module.h"
#include "ccpcv-detector.h"
#include "ccpcv-detector.cc"
#include "sim-logger.h"

#include <fstream>
#include <iomanip>
#include <cstdlib>
#include <limits>
#include <vector>
#include <map>
#include <string>
#include <cmath>
#include <random>
#include <algorithm>

using namespace ns3;

NS_LOG_COMPONENT_DEFINE("FakeBsSimulation");

// LTE Timing Advance step: c * 16 * Ts / 2, Ts = 1/30.72e6 s
static const double LTE_TA_STEP_M = 78.125;

// Fixed PLMN for this simulation (MCC=001, MNC=01)
static const uint32_t SIM_MCC = 1;
static const uint32_t SIM_MNC = 1;

// =============================================================================
// Log-normal shadowing noise
//
// Each RSRP sample is corrupted by an independent Gaussian draw:
//   rsrp_noisy = rsrp_clean + N(0, sigma_sh^2)
//
// sigma_sh is set by --shadowingStd (default 8 dB per COST-231 urban macro).
// Set to 0 to disable noise (noiseless, deterministic simulation).
// =============================================================================
static double             g_shadowingStdDb = 8.0;
static uint32_t           g_shadowingSeed  = 1;
static std::mt19937       g_shadowRng;
static std::normal_distribution<double> g_shadowDist{0.0, 1.0};

// Maximum number of cells per UE measurement report (models 3GPP maxReportCells IE).
// In real LTE, UE reports at most N strongest cells. 0 = no limit (report all).
static uint32_t           g_maxReportCells = 5;

// =============================================================================
// MeasReportConfig — models the RRC Measurement Configuration sent by eNB
//
// In real LTE, eNB sends RRCConnectionReconfiguration → measConfig which
// contains:
//   measObjectEUTRA : frequency + cell list to measure
//   reportConfig    : what to report (RSRP/RSRQ) + trigger (periodic/event)
//   cellIdReporting : when true, UE includes ECGI of each reported cell
//   reportInterval  : periodic reporting interval
//
// This struct captures the relevant parameters; PeriodicMeasure() uses it
// to generate measurement reports that include ECGI for every visible cell.
// =============================================================================
struct MeasReportConfig
{
    bool   cellIdReporting; // true → UE includes ECGI in measurement report
    double intervalSec;     // reporting interval [s] (mapped from reportInterval IE)
};
static MeasReportConfig g_measReportCfg;

// =============================================================================
// CellRecord
// =============================================================================
struct CellRecord
{
    uint16_t cellId;        // ns-3 internal ID (unique per device)
    EcgiT    ecgi;          // ECGI (globally unique; fake shares one legal ECGI)
    double   posX;
    double   posY;
    double   posZ;          // antenna height [m]
    double   txPowerDbm;
    bool     isFake;
};

// =============================================================================
// GlobalCellDatabase — singleton
// =============================================================================
class GlobalCellDatabase
{
public:
    static GlobalCellDatabase& Instance()
    {
        static GlobalCellDatabase inst;
        return inst;
    }

    void RegisterCell(uint16_t cellId, EcgiT ecgi,
                      double posX, double posY, double posZ,
                      double txPowerDbm, bool isFake)
    {
        m_cells[cellId] = CellRecord{cellId, ecgi, posX, posY, posZ, txPowerDbm, isFake};
        SIM_LOG(DEBUG, "GlobalCellDB",
                "registered cellId=" << cellId
                << " ECGI=" << EcgiToStr(ecgi)
                << (isFake ? " [FAKE]" : " [legal]")
                << " pos=(" << posX << "," << posY << "," << posZ << ")"
                << " txPower=" << txPowerDbm << "dBm");
    }

    // All cells (legal + fake)
    // Columns: ecgi, pos_x, pos_y, tx_power_dbm, is_fake
    void ExportCsv(const std::string& path) const
    {
        std::ofstream ofs(path);
        if (!ofs.is_open())
        {
            SIM_LOG(ERR, "GlobalCellDB",
                    "Cannot open cell_database CSV: " << path);
            return;
        }
        ofs << "ecgi,pos_x,pos_y,pos_z,tx_power_dbm,is_fake\n";
        for (const auto& kv : m_cells)
        {
            const CellRecord& r = kv.second;
            ofs << EcgiToStr(r.ecgi) << ","
                << std::fixed << std::setprecision(3)
                << r.posX       << ","
                << r.posY       << ","
                << r.posZ       << ","
                << r.txPowerDbm << ","
                << (r.isFake ? 1 : 0) << "\n";
        }
        SIM_LOG(INFO, "GlobalCellDB",
                "Cell database exported → " << path
                << "  (" << m_cells.size() << " cells)");
    }

    // Legal cells only
    // Columns: ecgi, pos_x, pos_y, tx_power_dbm
    void ExportLegalMapCsv(const std::string& path) const
    {
        std::ofstream ofs(path);
        if (!ofs.is_open())
        {
            SIM_LOG(ERR, "GlobalCellDB",
                    "Cannot open legal_cell_map CSV: " << path);
            return;
        }
        ofs << "ecgi,pos_x,pos_y,pos_z,tx_power_dbm\n";
        uint32_t count = 0;
        for (const auto& kv : m_cells)
        {
            const CellRecord& r = kv.second;
            if (r.isFake) continue;
            ofs << EcgiToStr(r.ecgi) << ","
                << std::fixed << std::setprecision(3)
                << r.posX       << ","
                << r.posY       << ","
                << r.posZ       << ","
                << r.txPowerDbm << "\n";
            ++count;
        }
        SIM_LOG(INFO, "GlobalCellDB",
                "Legal cell map exported → " << path
                << "  (" << count << " cells)");
    }

    const std::map<uint16_t, CellRecord>& GetCells() const { return m_cells; }

private:
    GlobalCellDatabase() = default;
    std::map<uint16_t, CellRecord> m_cells; // cellId → CellRecord
};

// =============================================================================
// MeasurementRecord — one row in measurements.csv
//
// One record per (UE, ECGI) per interval.
// cell_role: S = serving (strongest ECGI), N = neighbour
// Includes ECGI as configured by eNB via MeasReportConfig.cellIdReporting.
// =============================================================================
struct MeasurementRecord
{
    double   timeSec;
    uint64_t imsi;
    double   ueX;
    double   ueY;
    double   ueZ;
    uint16_t cellId;      // ns-3 unique cell ID (distinguishes fake vs legal even with same ECGI)
    EcgiT    ecgi;
    bool     isServing;
    double   rsrpDbm;
    int      timingAdvance;
};

// =============================================================================
// GlobalMeasurementCollector — singleton
// =============================================================================
class GlobalMeasurementCollector
{
public:
    static GlobalMeasurementCollector& Instance()
    {
        static GlobalMeasurementCollector inst;
        return inst;
    }

    void Open(const std::string& path)
    {
        m_ofs.open(path);
        if (!m_ofs.is_open())
        {
            SIM_LOG(ERR, "MeasureColl",
                    "Cannot open measurements CSV: " << path);
            return;
        }
        // cell_id: unique ns-3 cell ID (fake and legal have different cell_id even with same ECGI)
        // ecgi column included per MeasReportConfig.cellIdReporting = true
        m_ofs << "time_sec,imsi,ue_x,ue_y,ue_z,cell_id,ecgi,cell_role,rsrp_dbm,timing_advance\n";
        SIM_LOG(INFO, "MeasureColl", "Measurements CSV opened: " << path);
    }

    // Open separate CSV for UEs whose serving cell is the fake BS
    void OpenFakeServed(const std::string& path)
    {
        m_fakeOfs.open(path);
        if (!m_fakeOfs.is_open())
        {
            SIM_LOG(ERR, "MeasureColl",
                    "Cannot open fake_served_ues CSV: " << path);
            return;
        }
        m_fakeOfs << "time_sec,imsi,ue_x,ue_y,ue_z,serving_ecgi,rsrp_dbm,timing_advance\n";
        SIM_LOG(INFO, "MeasureColl", "Fake-served UEs CSV opened: " << path);
    }

    void AddMeasurement(const MeasurementRecord& rec)
    {
        if (!m_ofs.is_open()) return;
        m_ofs << std::fixed << std::setprecision(3)
              << rec.timeSec                 << ","
              << rec.imsi                    << ","
              << rec.ueX                     << ","
              << rec.ueY                     << ","
              << rec.ueZ                     << ","
              << rec.cellId                  << ","
              << EcgiToStr(rec.ecgi)         << ","
              << (rec.isServing ? "S" : "N") << ","
              << rec.rsrpDbm                 << ","
              << rec.timingAdvance           << "\n";
        m_ofs.flush();
    }

    // Write one row for a UE currently camped on the fake BS
    void AddFakeServed(double timeSec, uint64_t imsi,
                       double ueX, double ueY, double ueZ,
                       EcgiT servEcgi, double rsrpDbm, int ta)
    {
        if (!m_fakeOfs.is_open()) return;
        m_fakeOfs << std::fixed << std::setprecision(3)
                  << timeSec              << ","
                  << imsi                 << ","
                  << ueX                  << ","
                  << ueY                  << ","
                  << ueZ                  << ","
                  << EcgiToStr(servEcgi)  << ","
                  << rsrpDbm              << ","
                  << ta                   << "\n";
        m_fakeOfs.flush();
    }

    void Close()
    {
        if (m_ofs.is_open())     m_ofs.close();
        if (m_fakeOfs.is_open()) m_fakeOfs.close();
    }

private:
    GlobalMeasurementCollector() = default;
    std::ofstream m_ofs;
    std::ofstream m_fakeOfs;
};

// =============================================================================
// Globals
// =============================================================================

struct UeInfo { uint64_t imsi; Ptr<MobilityModel> mob; };
static std::map<uint32_t, UeInfo> g_ueByNodeId;

static std::string g_outputDir;
static double      g_txPowerDbm     = 46.0;
static double      g_fakeTxPowerDbm = 46.0;  // FBS TX power (may differ from LBS)

static CcpcvDetector g_ccpcvDetector;

// =============================================================================
// PeriodicMeasure — generates UE measurement reports as configured by eNB
//
// Models LTE periodic measurement reporting (reportInterval from eNB config):
//   - UE measures RSRP from every visible cell
//   - Cells identified by ECGI (cellIdReporting = true per MeasReportConfig)
//   - When fake and legal share an ECGI, UE reports the stronger signal
//   - Serving ECGI = ECGI with highest RSRP
//   - One CSV row per (UE, ECGI): serving + all neighbours
//
// Path-loss: PL[dB] = 128.1 + 37.6*log10(d_km)  (COST-231 urban macro, 2 GHz)
// =============================================================================
static void
PeriodicMeasure()
{
    double now = Simulator::Now().GetSeconds();
    const auto& cells = GlobalCellDatabase::Instance().GetCells();

    SIM_LOG(DEBUG, "PeriodicMeas",
            "t=" << std::fixed << std::setprecision(2) << now << "s"
            << "  generating measurement reports"
            << "  cellIdReporting=" << (g_measReportCfg.cellIdReporting ? "true" : "false"));

    for (auto& kv : g_ueByNodeId)
    {
        uint64_t imsi = kv.second.imsi;
        Vector   p    = kv.second.mob->GetPosition();
        double   ueX  = p.x;
        double   ueY  = p.y;
        // RandomWaypointMobilityModel resets z to 0 at each waypoint
        // (RandomRectanglePositionAllocator only generates x,y).
        // Force UE height to 2 m (handheld device).
        double   ueZ  = 2.0;

        // --- Aggregate RSRP + TA per ECGI (max RSRP wins on ECGI collision) ---
        // When fake and legal share an ECGI, the UE sees the stronger signal,
        // which is what it would report in a real measurement report.
        struct EcgiMeas { double rsrp; int ta; bool fromFake; uint16_t cellId; };
        std::map<EcgiT, EcgiMeas> ecgiMeas;

        for (const auto& cv : cells)
        {
            const CellRecord& cr = cv.second;
            double dx     = ueX - cr.posX;
            double dy     = ueY - cr.posY;
            double dz     = ueZ - cr.posZ;
            double dist   = std::max(std::sqrt(dx*dx + dy*dy + dz*dz), 1.0);
            double distKm = dist / 1000.0;
            double pl     = 128.1 + 37.6 * std::log10(distKm);
            double shadow = (g_shadowingStdDb > 0.0)
                            ? g_shadowingStdDb * g_shadowDist(g_shadowRng)
                            : 0.0;
            double rsrp   = cr.txPowerDbm - pl + shadow;
            int    ta     = static_cast<int>(std::round(dist / LTE_TA_STEP_M));

            auto it = ecgiMeas.find(cr.ecgi);
            if (it == ecgiMeas.end() || rsrp > it->second.rsrp)
                ecgiMeas[cr.ecgi] = {rsrp, ta, cr.isFake, cr.cellId};
        }

        // --- Trim to top-N cells by RSRP (models 3GPP maxReportCells) ---
        // In real LTE, the UE reports at most maxReportCells strongest cells.
        // The serving cell (highest RSRP) is always retained since it leads the list.
        if (g_maxReportCells > 0 && ecgiMeas.size() > g_maxReportCells)
        {
            // Sort ECGIs by RSRP descending
            std::vector<std::pair<double, EcgiT>> ranked;
            ranked.reserve(ecgiMeas.size());
            for (const auto& em : ecgiMeas)
                ranked.push_back({em.second.rsrp, em.first});
            std::sort(ranked.begin(), ranked.end(),
                      [](const std::pair<double,EcgiT>& a,
                         const std::pair<double,EcgiT>& b){ return a.first > b.first; });

            std::map<EcgiT, EcgiMeas> trimmed;
            for (uint32_t k = 0; k < g_maxReportCells; ++k)
                trimmed[ranked[k].second] = ecgiMeas[ranked[k].second];

            SIM_LOG(DEBUG, "PeriodicMeas",
                    "t=" << std::fixed << std::setprecision(2) << now << "s"
                    << " IMSI=" << imsi
                    << " trimmed ecgiMeas " << ecgiMeas.size()
                    << " → " << trimmed.size() << " cells (maxReportCells="
                    << g_maxReportCells << ")");

            ecgiMeas = trimmed;
        }

        // --- Log ECGI collision: fake signal stronger than legal ---
        for (const auto& em : ecgiMeas)
        {
            if (em.second.fromFake)
                SIM_LOG(DEBUG, "PeriodicMeas",
                        "t=" << std::fixed << std::setprecision(2) << now << "s"
                        << " IMSI=" << imsi
                        << " ECGI=" << EcgiToStr(em.first)
                        << " FAKE signal dominant"
                        << " rsrp=" << std::setprecision(1)
                        << em.second.rsrp << "dBm");
        }

        // --- Serving ECGI = ECGI with max RSRP ---
        EcgiT  servEcgi  = 0;
        double servRsrp  = -300.0;
        for (const auto& em : ecgiMeas)
        {
            if (em.second.rsrp > servRsrp)
            {
                servRsrp = em.second.rsrp;
                servEcgi = em.first;
            }
        }
        if (servEcgi == 0)
        {
            SIM_LOG(WARN, "PeriodicMeas",
                    "t=" << now << "s IMSI=" << imsi
                    << " — no visible ECGI, skipping");
            continue;
        }

        // --- Filter: if fake BS is the serving cell, record to fake_served_ues.csv
        //            and skip the main measurement report (detector only sees legal-served UEs).
        if (ecgiMeas[servEcgi].fromFake)
        {
            const EcgiMeas& em = ecgiMeas[servEcgi];
            GlobalMeasurementCollector::Instance().AddFakeServed(
                now, imsi, ueX, ueY, ueZ, servEcgi, em.rsrp, em.ta);
            SIM_LOG(DEBUG, "PeriodicMeas",
                    "t=" << std::fixed << std::setprecision(2) << now << "s"
                    << " IMSI=" << imsi
                    << " fake BS is serving (ECGI=" << EcgiToStr(servEcgi) << ")"
                    << " rsrp=" << std::setprecision(1) << em.rsrp << "dBm"
                    << " — recorded to fake_served_ues.csv, excluded from measurements.csv");
            continue;
        }

        // --- Write measurement report: one row per (UE, ECGI) ---
        // Legal cell is serving; all neighbour rows (including fake as neighbour) are kept.
        for (const auto& em : ecgiMeas)
        {
            MeasurementRecord rec;
            rec.timeSec       = now;
            rec.imsi          = imsi;
            rec.ueX           = ueX;
            rec.ueY           = ueY;
            rec.ueZ           = ueZ;
            rec.cellId        = em.second.cellId;
            rec.ecgi          = em.first;
            rec.isServing     = (em.first == servEcgi);
            rec.rsrpDbm       = em.second.rsrp;
            rec.timingAdvance = em.second.ta;
            GlobalMeasurementCollector::Instance().AddMeasurement(rec);
        }

        SIM_LOG(DEBUG, "PeriodicMeas",
                "t=" << std::fixed << std::setprecision(2) << now << "s"
                << " IMSI=" << imsi
                << " pos=(" << std::setprecision(1) << ueX << "," << ueY << ")"
                << " servECGI=" << EcgiToStr(servEcgi)
                << " rsrp=" << std::setprecision(1) << servRsrp << "dBm"
                << " ta=" << ecgiMeas[servEcgi].ta
                << " ecgis=" << ecgiMeas.size());

        // --- Feed MeasurementSample (keyed by ECGI) to CC-PCV detector ---
        MeasurementSample sample;
        sample.ueId = imsi;
        sample.time = now;
        sample.ueX  = ueX;
        sample.ueY  = ueY;
        sample.ueZ  = ueZ;
        for (const auto& em : ecgiMeas)
            sample.rsrpDbm[em.first] = em.second.rsrp;
        g_ccpcvDetector.AddSample(sample);
    }

    SIM_LOG(INFO, "PeriodicMeas",
            "t=" << std::fixed << std::setprecision(2) << now << "s"
            << "  UEs=" << g_ueByNodeId.size()
            << "  totalSamples=" << g_ccpcvDetector.SampleCount());

    Simulator::Schedule(Seconds(g_measReportCfg.intervalSec), &PeriodicMeasure);
}

// =============================================================================
// main
// =============================================================================
int
main(int argc, char* argv[])
{
    // -------------------------------------------------------------------------
    // Simulation parameters
    // -------------------------------------------------------------------------
    uint32_t    gridSize            = 3;
    double      isd                 = 500.0;
    uint32_t    numUe               = 20;
    double      simTimeSec          = 30.0;
    double      detectorIntervalSec = 1.0;
    double      fakePosX            = 750.0;
    double      fakePosY            = 750.0;
    uint32_t    fakeEci             = 1;    // ECI the fake BS impersonates
    double      txPowerDbm          = 46.0;
    double      fakeTxPowerDbm      = -1.0;   // <0 = same as txPowerDbm
    uint32_t    bandwidth           = 25;
    std::string outputDir           = "output";
    // FBS distance-based placement
    double      fbsDistFromLbs      = 0.0;   // 0 = use fakePosX/Y directly
    double      fbsAngleDeg         = 45.0;  // direction from target LBS to FBS [degrees]

    CommandLine cmd(__FILE__);
    cmd.AddValue("gridSize",         "Legal eNB grid dimension (NxN)",      gridSize);
    cmd.AddValue("isd",              "Inter-site distance [m]",             isd);
    cmd.AddValue("numUe",            "Number of UEs",                       numUe);
    cmd.AddValue("simTime",          "Simulation duration [s]",             simTimeSec);
    cmd.AddValue("detectorInterval", "Measurement reporting interval [s]",  detectorIntervalSec);
    cmd.AddValue("fakePosX",         "Fake BS X position [m]",              fakePosX);
    cmd.AddValue("fakePosY",         "Fake BS Y position [m]",              fakePosY);
    cmd.AddValue("fakeEci",          "ECI the fake BS impersonates (1..N)", fakeEci);
    cmd.AddValue("txPower",          "LBS Tx power [dBm]",                  txPowerDbm);
    cmd.AddValue("fakeTxPower",      "FBS Tx power [dBm] (-1 = same as txPower)", fakeTxPowerDbm);
    cmd.AddValue("bandwidth",        "Bandwidth in resource blocks",        bandwidth);
    cmd.AddValue("shadowingStd",     "Log-normal shadowing std-dev [dB] (0=disable)", g_shadowingStdDb);
    cmd.AddValue("shadowingSeed",    "RNG seed for shadowing noise",        g_shadowingSeed);
    cmd.AddValue("maxReportCells",   "Max cells per UE measurement report (0=all)", g_maxReportCells);
    cmd.AddValue("outputDir",        "Output directory path",               outputDir);
    cmd.AddValue("fbsDistFromLbs",   "FBS distance from target LBS [m] (0 = use fakePosX/Y)", fbsDistFromLbs);
    cmd.AddValue("fbsAngleDeg",      "Direction from target LBS to FBS [degrees, 0=East]",    fbsAngleDeg);
    cmd.Parse(argc, argv);

    g_outputDir      = outputDir;
    g_txPowerDbm     = txPowerDbm;
    g_fakeTxPowerDbm = (fakeTxPowerDbm < 0.0) ? txPowerDbm : fakeTxPowerDbm;

    // Seed the shadowing RNG
    g_shadowRng.seed(g_shadowingSeed);

    // Configure measurement reporting (models RRC MeasConfig from eNB)
    g_measReportCfg.cellIdReporting = true;
    g_measReportCfg.intervalSec     = detectorIntervalSec;

    // ECGI the fake BS will impersonate
    EcgiT fakeEcgi = MakeEcgi(SIM_MCC, SIM_MNC, fakeEci);

    // -------------------------------------------------------------------------
    // Open logger
    // -------------------------------------------------------------------------
    {
        int mkRet = std::system(("mkdir -p " + outputDir).c_str());
        if (mkRet != 0)
            std::cerr << "[run] mkdir -p " << outputDir
                      << " returned " << mkRet << "\n";
    }
    SimLogger::Get().Open(outputDir + "/simulation.log");
    SimLogger::Get().simTimeGetter = []() {
        return Simulator::Now().GetSeconds();
    };
    SimLogger::Get().minLevel = SimLogLevel::DEBUG;

    SIM_LOG(INFO, "FakeBsSim", "=== Simulation starting ===");
    SIM_LOG(INFO, "FakeBsSim", "gridSize=" << gridSize
            << "  numLegalEnb=" << gridSize * gridSize
            << "  isd=" << isd << "m");
    SIM_LOG(INFO, "FakeBsSim", "numUe=" << numUe
            << "  simTime=" << simTimeSec << "s");
    SIM_LOG(INFO, "FakeBsSim", "MeasReportConfig:"
            << "  cellIdReporting=" << (g_measReportCfg.cellIdReporting ? "true" : "false")
            << "  intervalSec=" << g_measReportCfg.intervalSec << "s"
            << "  maxReportCells=" << g_maxReportCells
            << (g_maxReportCells == 0 ? " (all)" : ""));
    SIM_LOG(INFO, "FakeBsSim", "fakeBS pos=(" << fakePosX << "," << fakePosY << ")"
            << "  impersonates ECGI=" << EcgiToStr(fakeEcgi)
            << "  (fakeEci=" << fakeEci << ")"
            << "  fakeTxPower=" << g_fakeTxPowerDbm << "dBm"
            << "  lbsTxPower="  << txPowerDbm << "dBm"
            << "  BW=" << bandwidth << "RBs");
    SIM_LOG(INFO, "FakeBsSim", "PLMN: MCC="
            << std::setw(3) << std::setfill('0') << SIM_MCC
            << "  MNC=" << std::setw(2) << std::setfill('0') << SIM_MNC);
    SIM_LOG(INFO, "FakeBsSim", "outputDir=" << outputDir);

    // -------------------------------------------------------------------------
    // LTE helper
    // -------------------------------------------------------------------------
    Ptr<LteHelper> lteHelper = CreateObject<LteHelper>();
    lteHelper->SetAttribute("PathlossModel",
        StringValue("ns3::LogDistancePropagationLossModel"));
    lteHelper->SetPathlossModelAttribute("Exponent",    DoubleValue(3.76));  // COST-231: 37.6/10
    lteHelper->SetPathlossModelAttribute("ReferenceLoss", DoubleValue(128.1 - 37.6*3)); // = 15.3 dB at 1m

    lteHelper->SetSchedulerType("ns3::RrFfMacScheduler");
    lteHelper->SetEnbDeviceAttribute("DlBandwidth", UintegerValue(bandwidth));
    lteHelper->SetEnbDeviceAttribute("UlBandwidth", UintegerValue(bandwidth));
    lteHelper->SetEnbDeviceAttribute("DlEarfcn",    UintegerValue(100));
    lteHelper->SetEnbDeviceAttribute("UlEarfcn",    UintegerValue(18100));

    Ptr<PointToPointEpcHelper> epcHelper = CreateObject<PointToPointEpcHelper>();
    lteHelper->SetEpcHelper(epcHelper);

    // -------------------------------------------------------------------------
    // Remote host
    // -------------------------------------------------------------------------
    NodeContainer remoteHostContainer;
    remoteHostContainer.Create(1);
    Ptr<Node> remoteHost = remoteHostContainer.Get(0);

    InternetStackHelper internet;
    internet.Install(remoteHostContainer);

    PointToPointHelper p2p;
    p2p.SetDeviceAttribute("DataRate", DataRateValue(DataRate("100Gb/s")));
    p2p.SetChannelAttribute("Delay",   TimeValue(MilliSeconds(10)));

    NetDeviceContainer internetDevices =
        p2p.Install(epcHelper->GetPgwNode(), remoteHost);
    Ipv4AddressHelper ipv4h;
    ipv4h.SetBase("1.0.0.0", "255.0.0.0");
    ipv4h.Assign(internetDevices);

    Ipv4StaticRoutingHelper routingHelper;
    Ptr<Ipv4StaticRouting> remoteRouting =
        routingHelper.GetStaticRouting(remoteHost->GetObject<Ipv4>());
    remoteRouting->AddNetworkRouteTo(Ipv4Address("7.0.0.0"),
                                     Ipv4Mask("255.0.0.0"), 1);

    // -------------------------------------------------------------------------
    // Legal eNBs — gridSize × gridSize, constant position
    // ECGI assigned: MCC=001, MNC=01, ECI=1..N  (grid RowFirst order)
    // -------------------------------------------------------------------------
    uint32_t numLegalEnb = gridSize * gridSize;
    NodeContainer legalEnbNodes;
    legalEnbNodes.Create(numLegalEnb);

    Ptr<GridPositionAllocator> gridAlloc = CreateObject<GridPositionAllocator>();
    gridAlloc->SetAttribute("MinX",       DoubleValue(0.0));
    gridAlloc->SetAttribute("MinY",       DoubleValue(0.0));
    gridAlloc->SetAttribute("DeltaX",     DoubleValue(isd));
    gridAlloc->SetAttribute("DeltaY",     DoubleValue(isd));
    gridAlloc->SetAttribute("GridWidth",  UintegerValue(gridSize));
    gridAlloc->SetAttribute("LayoutType", StringValue("RowFirst"));

    MobilityHelper enbMob;
    enbMob.SetMobilityModel("ns3::ConstantPositionMobilityModel");
    enbMob.SetPositionAllocator(gridAlloc);
    enbMob.Install(legalEnbNodes);

    // Set legal eNB antenna height to 25 m
    for (uint32_t i = 0; i < legalEnbNodes.GetN(); ++i)
    {
        Ptr<MobilityModel> mob = legalEnbNodes.Get(i)->GetObject<MobilityModel>();
        Vector p = mob->GetPosition();
        mob->SetPosition(Vector(p.x, p.y, 25.0));
    }

    // -------------------------------------------------------------------------
    // Fake eNB — broadcasts with fakeEcgi (impersonates a legal cell)
    // -------------------------------------------------------------------------
    NodeContainer fakeEnbNodes;
    fakeEnbNodes.Create(1);

    // ── Resolve FBS position ──────────────────────────────────────────────────
    // When --fbsDistFromLbs > 0, ignore fakePosX/Y and compute the FBS position
    // as: target_LBS_pos + dist * (cos(angle), sin(angle)), then clamp to the
    // UE coverage area so FBS is always within the simulation bounds.
    //
    // When --fbsDistFromLbs == 0 (default), use fakePosX/Y directly.
    // ──────────────────────────────────────────────────────────────────────────
    double resolvedFbsX = fakePosX;
    double resolvedFbsY = fakePosY;

    if (fbsDistFromLbs > 0.0)
    {
        // Find the target LBS position (the one being impersonated)
        double lbsTargetX = 0.0, lbsTargetY = 0.0;
        bool   found = false;
        for (uint32_t i = 0; i < numLegalEnb; ++i)
        {
            if (i + 1 == fakeEci)   // ECI is 1-indexed
            {
                Vector p = legalEnbNodes.Get(i)
                               ->GetObject<MobilityModel>()->GetPosition();
                lbsTargetX = p.x;
                lbsTargetY = p.y;
                found = true;
                break;
            }
        }

        if (!found)
        {
            SIM_LOG(WARN, "FakeBsSim",
                    "fbsDistFromLbs: target LBS for fakeEci=" << fakeEci
                    << " not found, falling back to fakePosX/Y");
        }
        else
        {
            double angleRad = fbsAngleDeg * M_PI / 180.0;
            double candidateX = lbsTargetX + fbsDistFromLbs * std::cos(angleRad);
            double candidateY = lbsTargetY + fbsDistFromLbs * std::sin(angleRad);

            // Re-use ueAreaMin/ueAreaMax which are defined just below (UE section)
            // We need them here — compute them now from gridSize and isd.
            double areaMin = -isd / 2.0;
            double areaMax = (gridSize - 1) * isd + isd / 2.0;

            // Clamp to UE area bounds so FBS stays within the simulation
            resolvedFbsX = std::max(areaMin, std::min(areaMax, candidateX));
            resolvedFbsY = std::max(areaMin, std::min(areaMax, candidateY));

            SIM_LOG(INFO, "FakeBsSim",
                    "fbsDistFromLbs=" << fbsDistFromLbs << "m"
                    << "  angle=" << fbsAngleDeg << "°"
                    << "  targetLBS=(" << lbsTargetX << "," << lbsTargetY << ")"
                    << "  candidate=(" << candidateX << "," << candidateY << ")"
                    << "  resolved=(" << resolvedFbsX << "," << resolvedFbsY << ")"
                    << (resolvedFbsX != candidateX || resolvedFbsY != candidateY
                        ? "  [clamped to area]" : ""));
        }
    }

    Ptr<ListPositionAllocator> fakeAlloc = CreateObject<ListPositionAllocator>();
    fakeAlloc->Add(Vector(resolvedFbsX, resolvedFbsY, 2.0));  // FBS antenna height = 2 m

    MobilityHelper fakeMob;
    fakeMob.SetMobilityModel("ns3::ConstantPositionMobilityModel");
    fakeMob.SetPositionAllocator(fakeAlloc);
    fakeMob.Install(fakeEnbNodes);


    // -------------------------------------------------------------------------
    // Install LTE devices
    // -------------------------------------------------------------------------
    // Legal BSs
    Config::SetDefault("ns3::LteEnbPhy::TxPower", DoubleValue(txPowerDbm));
    NetDeviceContainer legalEnbDevs = lteHelper->InstallEnbDevice(legalEnbNodes);

    // Fake BS — may use a different TX power
    Config::SetDefault("ns3::LteEnbPhy::TxPower", DoubleValue(g_fakeTxPowerDbm));
    NetDeviceContainer fakeEnbDevs  = lteHelper->InstallEnbDevice(fakeEnbNodes);

    SIM_LOG(DEBUG, "FakeBsSim", "LTE devices installed.");

    // -------------------------------------------------------------------------
    // Register cells in GlobalCellDatabase
    //
    // Legal cell i (0-indexed, RowFirst):  ECI = i+1
    //                                      ECGI = MakeEcgi(001, 01, i+1)
    // Fake cell:                           ECGI = fakeEcgi  (same as target legal)
    //
    // CC-PCV: only LEGAL cell positions registered (keyed by ECGI).
    // Fake cell NOT registered in CC-PCV — detector finds inconsistency between
    // measured RSRP at fakeEcgi and expected RSRP from the legal position.
    // -------------------------------------------------------------------------
    for (uint32_t i = 0; i < numLegalEnb; ++i)
    {
        uint16_t cellId = DynamicCast<LteEnbNetDevice>(
                              legalEnbDevs.Get(i))->GetCellId();
        EcgiT    ecgi   = MakeEcgi(SIM_MCC, SIM_MNC, i + 1);
        Vector   pos    = legalEnbNodes.Get(i)
                            ->GetObject<MobilityModel>()->GetPosition();

        GlobalCellDatabase::Instance().RegisterCell(
            cellId, ecgi, pos.x, pos.y, pos.z, txPowerDbm, false);

        g_ccpcvDetector.SetCellPosition(ecgi, pos); // legal position known

        SIM_LOG(INFO, "FakeBsSim",
                "Legal eNB  cellId=" << cellId
                << "  ECGI=" << EcgiToStr(ecgi)
                << "  pos=(" << pos.x << "," << pos.y << ")");
    }
    {
        uint16_t cellId = DynamicCast<LteEnbNetDevice>(
                              fakeEnbDevs.Get(0))->GetCellId();
        Vector   pos    = fakeEnbNodes.Get(0)
                            ->GetObject<MobilityModel>()->GetPosition();

        GlobalCellDatabase::Instance().RegisterCell(
            cellId, fakeEcgi, pos.x, pos.y, pos.z, g_fakeTxPowerDbm, true);

        // Fake NOT registered in CC-PCV: we test signals at fakeEcgi against
        // the known LEGAL position for that ECGI → anomaly → detection.

        SIM_LOG(INFO, "FakeBsSim",
                "FAKE eNB  cellId=" << cellId
                << "  ECGI=" << EcgiToStr(fakeEcgi)
                << "  (impersonates legal ECGI=" << EcgiToStr(fakeEcgi) << ")"
                << "  pos=(" << pos.x << "," << pos.y << ")"
                << "  txPower=" << g_fakeTxPowerDbm << "dBm"
                << "  (LBS txPower=" << txPowerDbm << "dBm)");
    }

    // Validate fakeEci range
    if (fakeEci < 1 || fakeEci > numLegalEnb)
        SIM_LOG(WARN, "FakeBsSim",
                "fakeEci=" << fakeEci << " out of range [1.." << numLegalEnb
                << "] — detection may be degraded");

    // -------------------------------------------------------------------------
    // UEs — random-waypoint mobility over coverage area
    // -------------------------------------------------------------------------
    NodeContainer ueNodes;
    ueNodes.Create(numUe);

    // UE coverage area: each cell owns a symmetric ±isd/2 Voronoi region.
    // Cells span [0 .. (gridSize-1)*isd], so the fair UE area is
    // [-isd/2 .. (gridSize-1)*isd + isd/2], giving every cell equal area.
    double ueAreaMin = -isd / 2.0;
    double ueAreaMax = (gridSize - 1) * isd + isd / 2.0;

    Ptr<RandomRectanglePositionAllocator> ueArea =
        CreateObject<RandomRectanglePositionAllocator>();
    ueArea->SetAttribute("X",
        StringValue("ns3::UniformRandomVariable[Min="
                    + std::to_string(ueAreaMin) + "|Max="
                    + std::to_string(ueAreaMax) + "]"));
    ueArea->SetAttribute("Y",
        StringValue("ns3::UniformRandomVariable[Min="
                    + std::to_string(ueAreaMin) + "|Max="
                    + std::to_string(ueAreaMax) + "]"));

    MobilityHelper ueMob;
    ueMob.SetPositionAllocator(ueArea);
    ueMob.SetMobilityModel(
        "ns3::RandomWaypointMobilityModel",
        "Speed",  StringValue("ns3::UniformRandomVariable[Min=1.0|Max=15.0]"),
        "Pause",  StringValue("ns3::ConstantRandomVariable[Constant=0.0]"),
        "PositionAllocator", PointerValue(ueArea));
    ueMob.Install(ueNodes);

    // Set UE height to 2 m (handheld device height)
    for (uint32_t i = 0; i < ueNodes.GetN(); ++i)
    {
        Ptr<MobilityModel> mob = ueNodes.Get(i)->GetObject<MobilityModel>();
        Vector p = mob->GetPosition();
        mob->SetPosition(Vector(p.x, p.y, 2.0));
    }

    // -------------------------------------------------------------------------
    // Internet stack + LTE devices on UEs
    // -------------------------------------------------------------------------
    internet.Install(ueNodes);
    NetDeviceContainer ueDevs = lteHelper->InstallUeDevice(ueNodes);

    Ipv4InterfaceContainer ueIfaces = epcHelper->AssignUeIpv4Address(ueDevs);
    for (uint32_t i = 0; i < ueNodes.GetN(); ++i)
    {
        Ptr<Ipv4StaticRouting> r =
            routingHelper.GetStaticRouting(ueNodes.Get(i)->GetObject<Ipv4>());
        r->SetDefaultRoute(epcHelper->GetUeDefaultGatewayAddress(), 1);
    }

    // Attach each UE to nearest LEGAL eNB (prevent fake from winning attach)
    SIM_LOG(INFO, "FakeBsSim",
            "Attaching " << numUe << " UEs to nearest legal eNB...");
    for (uint32_t i = 0; i < ueNodes.GetN(); ++i)
    {
        Vector   uePos    = ueNodes.Get(i)
                              ->GetObject<MobilityModel>()->GetPosition();
        uint32_t nearestJ = 0;
        double   minDist  = std::numeric_limits<double>::max();

        for (uint32_t j = 0; j < numLegalEnb; ++j)
        {
            Vector enbPos = legalEnbNodes.Get(j)
                              ->GetObject<MobilityModel>()->GetPosition();
            double dx   = uePos.x - enbPos.x;
            double dy   = uePos.y - enbPos.y;
            double dist = std::sqrt(dx * dx + dy * dy);
            if (dist < minDist) { minDist = dist; nearestJ = j; }
        }

        lteHelper->Attach(ueDevs.Get(i), legalEnbDevs.Get(nearestJ));

        uint64_t imsi  = DynamicCast<LteUeNetDevice>(ueDevs.Get(i))->GetImsi();
        EcgiT    ecgi  = MakeEcgi(SIM_MCC, SIM_MNC, nearestJ + 1);
        SIM_LOG(DEBUG, "FakeBsSim",
                "UE IMSI=" << imsi
                << " → legal eNB[" << nearestJ << "]"
                << " ECGI=" << EcgiToStr(ecgi)
                << " dist=" << std::fixed << std::setprecision(1) << minDist << "m");
    }
    SIM_LOG(INFO, "FakeBsSim",
            "All " << numUe << " UEs attached to legal eNBs.");

    // -------------------------------------------------------------------------
    // UDP downlink traffic — keeps LTE scheduler active
    // -------------------------------------------------------------------------
    uint16_t dlPort = 1234;
    PacketSinkHelper dlSink("ns3::UdpSocketFactory",
                             InetSocketAddress(Ipv4Address::GetAny(), dlPort));

    ApplicationContainer serverApps, clientApps;
    for (uint32_t i = 0; i < ueNodes.GetN(); ++i)
    {
        serverApps.Add(dlSink.Install(ueNodes.Get(i)));
        UdpClientHelper dlClient(ueIfaces.GetAddress(i), dlPort);
        dlClient.SetAttribute("Interval",   TimeValue(MilliSeconds(100)));
        dlClient.SetAttribute("MaxPackets", UintegerValue(0xFFFFFFFF));
        dlClient.SetAttribute("PacketSize", UintegerValue(512));
        clientApps.Add(dlClient.Install(remoteHost));
    }
    serverApps.Start(Seconds(0.5));
    clientApps.Start(Seconds(1.0));
    serverApps.Stop(Seconds(simTimeSec));
    clientApps.Stop(Seconds(simTimeSec));

    SIM_LOG(DEBUG, "FakeBsSim",
            "UDP DL traffic: " << numUe << " flows, port=" << dlPort
            << ", 512B @100ms");

    // -------------------------------------------------------------------------
    // Build nodeId → UeInfo map
    // -------------------------------------------------------------------------
    for (uint32_t i = 0; i < ueNodes.GetN(); ++i)
    {
        uint32_t nodeId = ueNodes.Get(i)->GetId();
        uint64_t imsi   = DynamicCast<LteUeNetDevice>(ueDevs.Get(i))->GetImsi();
        g_ueByNodeId[nodeId] = UeInfo{imsi,
                                      ueNodes.Get(i)->GetObject<MobilityModel>()};
        SIM_LOG(DEBUG, "FakeBsSim",
                "UE map: nodeId=" << nodeId << " → IMSI=" << imsi);
    }
    SIM_LOG(INFO, "FakeBsSim",
            "UE map built: " << g_ueByNodeId.size() << " entries");

    // -------------------------------------------------------------------------
    // Open output files
    // -------------------------------------------------------------------------
    GlobalMeasurementCollector::Instance().Open(outputDir + "/measurements.csv");
    GlobalMeasurementCollector::Instance().OpenFakeServed(outputDir + "/fake_served_ues.csv");
    GlobalCellDatabase::Instance().ExportCsv(outputDir + "/cell_database.csv");
    GlobalCellDatabase::Instance().ExportLegalMapCsv(outputDir + "/legal_cell_map.csv");

    // -------------------------------------------------------------------------
    // Configure CC-PCV detector
    // -------------------------------------------------------------------------
    g_ccpcvDetector.areaMinX           = ueAreaMin;
    g_ccpcvDetector.areaMaxX           = ueAreaMax;
    g_ccpcvDetector.areaMinY           = ueAreaMin;
    g_ccpcvDetector.areaMaxY           = ueAreaMax;
    g_ccpcvDetector.pathLossExponent   = 3.76;  // COST-231 urban macro
    g_ccpcvDetector.txPowerDbm         = txPowerDbm;
    g_ccpcvDetector.gridResolutionM    = 50.0;
    g_ccpcvDetector.detectionThreshold = 1000.0;

    SIM_LOG(INFO, "FakeBsSim",
            "CC-PCV config: area=[" << ueAreaMin << ".." << ueAreaMax << "]x["
            << ueAreaMin << ".." << ueAreaMax << "]m"
            << "  grid=" << g_ccpcvDetector.gridResolutionM << "m"
            << "  threshold=" << g_ccpcvDetector.detectionThreshold
            << "  maxSampPerGroup=" << g_ccpcvDetector.maxSamplesPerGroup);

    // -------------------------------------------------------------------------
    // Schedule periodic measurement reporting
    // -------------------------------------------------------------------------
    Simulator::Schedule(Seconds(g_measReportCfg.intervalSec), &PeriodicMeasure);
    SIM_LOG(INFO, "FakeBsSim",
            "Measurement reporting scheduled every "
            << g_measReportCfg.intervalSec << "s"
            << "  (expected ~"
            << (uint64_t)(numUe * (simTimeSec / g_measReportCfg.intervalSec))
            << " UE reports)");

    // -------------------------------------------------------------------------
    // Run simulation
    // -------------------------------------------------------------------------
    Simulator::Stop(Seconds(simTimeSec));
    SIM_LOG(INFO, "FakeBsSim",
            "=== Simulator::Run() starting ==="
            "  legalEnbs=" << numLegalEnb <<
            "  fakeEnbs=1 (ECGI=" << EcgiToStr(fakeEcgi) << ")"
            "  UEs=" << numUe <<
            "  duration=" << simTimeSec << "s");
    Simulator::Run();

    SIM_LOG(INFO, "FakeBsSim",
            "=== Simulator::Run() finished ==="
            "  totalSamples=" << g_ccpcvDetector.SampleCount());

    // -------------------------------------------------------------------------
    // CC-PCV detection
    // -------------------------------------------------------------------------
    g_ccpcvDetector.outputCsvPath = outputDir + "/ccpcv_results.csv";
    SIM_LOG(INFO, "FakeBsSim", "Running CC-PCV detection...");
    g_ccpcvDetector.RunDetection();
    SIM_LOG(INFO, "FakeBsSim",
            "CC-PCV done. Detected fake ECGIs: "
            << g_ccpcvDetector.GetDetectedFakeEcgis().size());

    Simulator::Destroy();

    // -------------------------------------------------------------------------
    // Finalize
    // -------------------------------------------------------------------------
    GlobalMeasurementCollector::Instance().Close();

    SIM_LOG(INFO, "FakeBsSim", "=== All done. Results in: " << outputDir << " ===");
    SimLogger::Get().Close();
    return 0;
}
